// ========= SIDEBAR TOGGLE =========
const sidebarToggle = document.getElementById('sidebarToggle');
const sidebar = document.getElementById('voxifySidebar');
const layout = document.getElementById('voxifyLayout');
const overlay = document.getElementById('sidebarOverlay');

const isMobile = () => window.innerWidth <= 768;

if (sidebarToggle) {
    sidebarToggle.addEventListener('click', () => {
        if (isMobile()) {
            sidebar.classList.toggle('mobile-open');
            overlay.classList.toggle('show');
        } else {
            sidebar.classList.toggle('collapsed');
            layout.classList.toggle('sidebar-collapsed');
        }
    });
}

if (overlay) {
    overlay.addEventListener('click', () => {
        sidebar.classList.remove('mobile-open');
        overlay.classList.remove('show');
    });
}

window.addEventListener('resize', () => {
    if (!isMobile()) {
        sidebar.classList.remove('mobile-open');
        overlay.classList.remove('show');
    }
});

// ========= NAVBAR DROPDOWNS =========
const statusQuickBtn = document.getElementById('statusQuickBtn');
const statusDropdown = document.getElementById('statusDropdown');
const profileBtn = document.getElementById('profileBtn');
const profileDropdown = document.getElementById('profileDropdown');

if (statusQuickBtn) {
    statusQuickBtn.addEventListener('click', (e) => {
        e.stopPropagation();
        statusDropdown.classList.toggle('open');
        if (profileDropdown) profileDropdown.classList.remove('open');
    });
}

if (profileBtn) {
    profileBtn.addEventListener('click', (e) => {
        e.stopPropagation();
        profileDropdown.classList.toggle('open');
        if (statusDropdown) statusDropdown.classList.remove('open');
    });
}

document.addEventListener('click', () => {
    if (profileDropdown) profileDropdown.classList.remove('open');
    if (statusDropdown) statusDropdown.classList.remove('open');
});

// ========= TICKET DATA =========
const ticketsData = {
    'TKT-9901': {
        id: 'TKT-9901',
        title: 'Server Failure - Authentication Service',
        priority: 'critical',
        status: 'Resolved',
        customer: 'Enterprise Client - TechCorp',
        serviceType: 'Authentication Service',
        created: '2025-04-14T09:30:00',
        resolved: '2025-04-14T16:45:00',
        timeline: [
            { time: '14:00 PM', text: 'Ticket automatically generated by monitoring system after server health check failed.', type: 'success', user: 'System' },
            { time: '14:15 PM', text: 'Ticket assigned to Senior Engineer John for immediate investigation.', type: 'info', user: 'System' },
            { time: '15:30 PM', text: 'Engineer reached site and diagnostics started. Root cause identified as memory leak.', type: 'warning', user: 'John (Engineer)' },
            { time: '16:10 PM', text: 'Issue identified and fix applied. Server restart initiated.', type: 'primary', user: 'John (Engineer)' },
            { time: '16:45 PM', text: 'System restored and verified successfully. Customer notified.', type: 'success', user: 'System' }
        ]
    },
    'TKT-9902': {
        id: 'TKT-9902',
        title: 'Broadband Outage - Fiber Cut',
        priority: 'high',
        status: 'In Progress',
        customer: 'Residential - Goregaon Area',
        serviceType: 'Broadband Internet',
        created: '2025-04-14T08:15:00',
        resolved: null,
        timeline: [
            { time: '08:15 AM', text: 'Multiple complaints received from Goregaon area. Ticket created.', type: 'success', user: 'System' },
            { time: '08:30 AM', text: 'Ticket escalated to NOC team for immediate action.', type: 'info', user: 'System' },
            { time: '08:45 AM', text: 'Field technician dispatched to location.', type: 'info', user: 'Dispatch Team' },
            { time: '09:30 AM', text: 'Technician confirmed fiber optic cable damage. Repair in progress.', type: 'warning', user: 'Rahul (Technician)' },
            { time: '10:15 AM', text: 'ETA for restoration: 2 hours.', type: 'primary', user: 'System' }
        ]
    },
    'TKT-9903': {
        id: 'TKT-9903',
        title: 'Network Congestion - BKC',
        priority: 'medium',
        status: 'In Progress',
        customer: 'Business District - BKC',
        serviceType: 'Mobile Network',
        created: '2025-04-14T10:00:00',
        resolved: null,
        timeline: [
            { time: '10:00 AM', text: 'Ticket created from automated alert system.', type: 'success', user: 'System' },
            { time: '10:15 AM', text: 'Network team investigating high latency issue.', type: 'info', user: 'Network Team' },
            { time: '10:45 AM', text: 'Load balancing initiated to reduce congestion.', type: 'primary', user: 'System' }
        ]
    },
    'CMP-10234': {
        id: 'CMP-10234',
        title: 'Fiber Cut - Andheri West',
        priority: 'critical',
        status: 'Resolved',
        customer: 'Residential - Andheri West',
        serviceType: 'Broadband',
        created: '2025-04-13T18:20:00',
        resolved: '2025-04-14T09:30:00',
        timeline: [
            { time: '18:20 PM', text: 'Customer reported complete internet outage. Ticket created.', type: 'success', user: 'Customer' },
            { time: '19:00 PM', text: 'Ticket acknowledged and assigned to technician.', type: 'info', user: 'Support Agent' },
            { time: '21:30 PM', text: 'Technician dispatched for next-day morning repair.', type: 'info', user: 'Dispatch Team' },
            { time: '08:00 AM', text: 'Technician arrived at site. Fiber cut confirmed.', type: 'warning', user: 'Vikram (Technician)' },
            { time: '09:30 AM', text: 'Fiber spliced and internet restored. Customer notified.', type: 'success', user: 'System' }
        ]
    }
};

const relatedTickets = [
    { id: 'TKT-9904', title: 'DNS Resolution Issue', status: 'Open', priority: 'high' },
    { id: 'TKT-9905', title: 'Voice Call Problem', status: 'In Progress', priority: 'low' },
    { id: 'CMP-10567', title: 'Slow Internet Speed', status: 'Resolved', priority: 'medium' }
];

let currentTicketId = 'TKT-9901';

// ========= RENDER FUNCTIONS =========
function getPriorityClass(priority) {
    switch(priority) {
        case 'critical': return 'critical';
        case 'high': return 'high';
        case 'medium': return 'medium';
        case 'low': return 'low';
        default: return 'medium';
    }
}

function getPriorityDisplay(priority) {
    return priority.charAt(0).toUpperCase() + priority.slice(1);
}

function renderTicketDetails() {
    const ticket = ticketsData[currentTicketId];
    if (!ticket) return;
    
    // Update header
    const ticketTitle = document.getElementById('ticketTitle');
    const ticketSubtitle = document.getElementById('ticketSubtitle');
    const priorityBadge = document.getElementById('ticketPriorityBadge');
    
    if (ticketTitle) ticketTitle.textContent = `Ticket #${ticket.id}`;
    if (ticketSubtitle) ticketSubtitle.textContent = ticket.title;
    if (priorityBadge) {
        priorityBadge.textContent = getPriorityDisplay(ticket.priority);
        priorityBadge.className = `priority-badge ${getPriorityClass(ticket.priority)}`;
    }
    
    // Render ticket info
    const ticketInfo = document.getElementById('ticketInfo');
    if (ticketInfo) {
        ticketInfo.innerHTML = `
            <div class="info-item"><div class="info-label">Customer</div><div class="info-value">${ticket.customer}</div></div>
            <div class="info-item"><div class="info-label">Service Type</div><div class="info-value">${ticket.serviceType}</div></div>
            <div class="info-item"><div class="info-label">Created</div><div class="info-value">${new Date(ticket.created).toLocaleString()}</div></div>
            <div class="info-item"><div class="info-label">Status</div><div class="info-value"><span class="status-badge status-${ticket.status.toLowerCase().replace(' ', '')}">${ticket.status}</span></div></div>
            ${ticket.resolved ? `<div class="info-item"><div class="info-label">Resolved</div><div class="info-value">${new Date(ticket.resolved).toLocaleString()}</div></div>` : ''}
        `;
    }
    
    // Render timeline
    const timeline = document.getElementById('timeline');
    if (timeline) {
        timeline.innerHTML = ticket.timeline.map(item => `
            <div class="timeline-item">
                <div class="timeline-dot ${item.type}"></div>
                <div class="timeline-content">
                    <div class="timeline-time">🕐 ${item.time}</div>
                    <div class="timeline-text">${item.text}</div>
                    <div class="timeline-user">👤 ${item.user}</div>
                </div>
            </div>
        `).join('');
    }
}

function renderRelatedTickets() {
    const container = document.getElementById('relatedTicketsList');
    if (!container) return;
    
    container.innerHTML = relatedTickets.map(ticket => `
        <div class="related-ticket-item" onclick="selectRelatedTicket('${ticket.id}')">
            <div>
                <div class="related-ticket-id">${ticket.id}</div>
                <div class="related-ticket-title">${ticket.title}</div>
            </div>
            <div>
                <span class="priority-badge ${getPriorityClass(ticket.priority)}" style="font-size: 10px; padding: 2px 8px;">${getPriorityDisplay(ticket.priority)}</span>
                <span class="status-badge status-${ticket.status.toLowerCase().replace(' ', '')}" style="margin-left: 8px; font-size: 10px;">${ticket.status}</span>
            </div>
        </div>
    `).join('');
}

// ========= EVENT HANDLERS =========
window.selectRelatedTicket = function(ticketId) {
    if (ticketsData[ticketId]) {
        currentTicketId = ticketId;
        const ticketSelect = document.getElementById('ticketSelect');
        if (ticketSelect) ticketSelect.value = ticketId;
        renderTicketDetails();
        showToast(`Switched to ticket ${ticketId}`, 'info');
    } else {
        showToast(`Ticket ${ticketId} details not available`, 'error');
    }
};

const viewTicketBtn = document.getElementById('viewTicketBtn');
if (viewTicketBtn) {
    viewTicketBtn.addEventListener('click', () => {
        const select = document.getElementById('ticketSelect');
        if (select) {
            currentTicketId = select.value;
            renderTicketDetails();
            showToast(`Loading ticket ${currentTicketId}`, 'success');
        }
    });
}

const exportTimelineBtn = document.getElementById('exportTimelineBtn');
if (exportTimelineBtn) {
    exportTimelineBtn.addEventListener('click', () => {
        const ticket = ticketsData[currentTicketId];
        if (ticket) {
            let exportText = `Ticket #${ticket.id}\n${ticket.title}\n${'-'.repeat(50)}\n\n`;
            exportText += `Customer: ${ticket.customer}\n`;
            exportText += `Service: ${ticket.serviceType}\n`;
            exportText += `Created: ${new Date(ticket.created).toLocaleString()}\n`;
            exportText += `Status: ${ticket.status}\n`;
            exportText += `${'-'.repeat(50)}\n\nTIMELINE:\n`;
            
            ticket.timeline.forEach(item => {
                exportText += `[${item.time}] ${item.text} (${item.user})\n`;
            });
            
            const blob = new Blob([exportText], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `ticket-${ticket.id}-timeline.txt`;
            a.click();
            URL.revokeObjectURL(url);
            showToast('Timeline exported successfully', 'success');
        }
    });
}

const shareTicketBtn = document.getElementById('shareTicketBtn');
if (shareTicketBtn) {
    shareTicketBtn.addEventListener('click', () => {
        showToast(`Ticket ${currentTicketId} shared with team via email`, 'success');
    });
}

// ========= TOAST FUNCTION =========
let toastTimer;
function showToast(message, type = 'success') {
    const toast = document.getElementById('toast');
    const toastMsg = document.getElementById('toastMsg');
    const icon = toast?.querySelector('svg');
    
    if (!toast || !toastMsg) return;
    
    toastMsg.textContent = message;
    toast.className = 'toast ' + type;
    
    if (type === 'error') {
        if (icon) icon.innerHTML = '<line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>';
        toast.style.background = '#b82030';
    } else if (type === 'warning') {
        if (icon) icon.innerHTML = '<circle cx="12" cy="12" r="10"/><line x1="12" y1="12" x2="12" y2="16"/><line x1="12" y1="8" x2="12.01" y2="8"/>';
        toast.style.background = '#E67E22';
    } else if (type === 'info') {
        if (icon) icon.innerHTML = '<circle cx="12" cy="12" r="10"/><line x1="12" y1="12" x2="12" y2="16"/><line x1="12" y1="8" x2="12.01" y2="8"/>';
        toast.style.background = '#1a1a1a';
    } else {
        if (icon) icon.innerHTML = '<polyline points="20 6 9 17 4 12"/>';
        toast.style.background = '#1a1a1a';
    }
    
    toast.classList.add('show');
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => toast.classList.remove('show'), 3000);
}

// ========= INITIALIZE =========
function init() {
    renderTicketDetails();
    renderRelatedTickets();
}

init();

// Export for global use
window.showToast = showToast;
window.selectRelatedTicket = selectRelatedTicket;